name: Terraform — ai-knowledge-assistant infra

on:
  push:
    branches: [dev]
    paths:
      - 'infra/**'
      - 'lambda/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Operación Terraform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

# id-token: write is indeed for using OIDC, Actions ask for JWT (AWS temporary credentials)
# contents: read as default
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: '1.9.0'
  # EVA_ALARM_EMAIL
  TF_VAR_alarm_email: ${{ secrets.EVA_ALARM_EMAIL }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654225860:role/github-actions-ai-kb-tf
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan -no-color

      - name: Terraform apply
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: terraform apply -auto-approve tfplan

      - name: Terraform destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

      - name: Terraform outputs
        if: success()
        run: terraform output
